/*
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class DomainStandaloneSetup extends DomainStandaloneSetupGenerated {

	def static void doSetup() {
		new DomainStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
