/*
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDomainScopeProvider extends DelegatingScopeProvider {
}
