/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.gmse.domain.DomainPackage;
import org.xtext.gmse.domain.Food;
import org.xtext.gmse.domain.FoodLineup;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Food Lineup</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gmse.domain.impl.FoodLineupImpl#getFoodlist <em>Foodlist</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FoodLineupImpl extends MinimalEObjectImpl.Container implements FoodLineup
{
  /**
   * The cached value of the '{@link #getFoodlist() <em>Foodlist</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFoodlist()
   * @generated
   * @ordered
   */
  protected EList<Food> foodlist;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FoodLineupImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainPackage.Literals.FOOD_LINEUP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Food> getFoodlist()
  {
    if (foodlist == null)
    {
      foodlist = new EObjectContainmentEList<Food>(Food.class, this, DomainPackage.FOOD_LINEUP__FOODLIST);
    }
    return foodlist;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DomainPackage.FOOD_LINEUP__FOODLIST:
        return ((InternalEList<?>)getFoodlist()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainPackage.FOOD_LINEUP__FOODLIST:
        return getFoodlist();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainPackage.FOOD_LINEUP__FOODLIST:
        getFoodlist().clear();
        getFoodlist().addAll((Collection<? extends Food>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainPackage.FOOD_LINEUP__FOODLIST:
        getFoodlist().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainPackage.FOOD_LINEUP__FOODLIST:
        return foodlist != null && !foodlist.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FoodLineupImpl
