/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.gmse.domain.Artist;
import org.xtext.gmse.domain.DomainPackage;
import org.xtext.gmse.domain.Lineup;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Lineup</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gmse.domain.impl.LineupImpl#getArtists <em>Artists</em>}</li>
 * </ul>
 *
 * @generated
 */
public class LineupImpl extends MinimalEObjectImpl.Container implements Lineup
{
  /**
   * The cached value of the '{@link #getArtists() <em>Artists</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArtists()
   * @generated
   * @ordered
   */
  protected EList<Artist> artists;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected LineupImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DomainPackage.Literals.LINEUP;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Artist> getArtists()
  {
    if (artists == null)
    {
      artists = new EObjectContainmentEList<Artist>(Artist.class, this, DomainPackage.LINEUP__ARTISTS);
    }
    return artists;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case DomainPackage.LINEUP__ARTISTS:
        return ((InternalEList<?>)getArtists()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case DomainPackage.LINEUP__ARTISTS:
        return getArtists();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case DomainPackage.LINEUP__ARTISTS:
        getArtists().clear();
        getArtists().addAll((Collection<? extends Artist>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case DomainPackage.LINEUP__ARTISTS:
        getArtists().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case DomainPackage.LINEUP__ARTISTS:
        return artists != null && !artists.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //LineupImpl
