/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>days</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.gmse.domain.DomainPackage#getdays()
 * @model
 * @generated
 */
public enum days implements Enumerator
{
  /**
   * The '<em><b>THURSDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THURSDAY_VALUE
   * @generated
   * @ordered
   */
  THURSDAY(0, "THURSDAY", "Donnerstag"),

  /**
   * The '<em><b>FRIDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FRIDAY_VALUE
   * @generated
   * @ordered
   */
  FRIDAY(1, "FRIDAY", "Freitag"),

  /**
   * The '<em><b>SATURDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SATURDAY_VALUE
   * @generated
   * @ordered
   */
  SATURDAY(2, "SATURDAY", "Samstag"),

  /**
   * The '<em><b>SUNDAY</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SUNDAY_VALUE
   * @generated
   * @ordered
   */
  SUNDAY(3, "SUNDAY", "Sonntag");

  /**
   * The '<em><b>THURSDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THURSDAY
   * @model literal="Donnerstag"
   * @generated
   * @ordered
   */
  public static final int THURSDAY_VALUE = 0;

  /**
   * The '<em><b>FRIDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FRIDAY
   * @model literal="Freitag"
   * @generated
   * @ordered
   */
  public static final int FRIDAY_VALUE = 1;

  /**
   * The '<em><b>SATURDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SATURDAY
   * @model literal="Samstag"
   * @generated
   * @ordered
   */
  public static final int SATURDAY_VALUE = 2;

  /**
   * The '<em><b>SUNDAY</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SUNDAY
   * @model literal="Sonntag"
   * @generated
   * @ordered
   */
  public static final int SUNDAY_VALUE = 3;

  /**
   * An array of all the '<em><b>days</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final days[] VALUES_ARRAY =
    new days[]
    {
      THURSDAY,
      FRIDAY,
      SATURDAY,
      SUNDAY,
    };

  /**
   * A public read-only list of all the '<em><b>days</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<days> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>days</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static days get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      days result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>days</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static days getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      days result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>days</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static days get(int value)
  {
    switch (value)
    {
      case THURSDAY_VALUE: return THURSDAY;
      case FRIDAY_VALUE: return FRIDAY;
      case SATURDAY_VALUE: return SATURDAY;
      case SUNDAY_VALUE: return SUNDAY;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private days(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //days
