/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.gmse.domain.DomainPackage
 * @generated
 */
public interface DomainFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DomainFactory eINSTANCE = org.xtext.gmse.domain.impl.DomainFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Festival</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Festival</em>'.
   * @generated
   */
  Festival createFestival();

  /**
   * Returns a new object of class '<em>Lineup</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Lineup</em>'.
   * @generated
   */
  Lineup createLineup();

  /**
   * Returns a new object of class '<em>Artist</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Artist</em>'.
   * @generated
   */
  Artist createArtist();

  /**
   * Returns a new object of class '<em>Stagelist</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stagelist</em>'.
   * @generated
   */
  Stagelist createStagelist();

  /**
   * Returns a new object of class '<em>Stage</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Stage</em>'.
   * @generated
   */
  Stage createStage();

  /**
   * Returns a new object of class '<em>Timetable</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timetable</em>'.
   * @generated
   */
  Timetable createTimetable();

  /**
   * Returns a new object of class '<em>Timetable Entry</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Timetable Entry</em>'.
   * @generated
   */
  TimetableEntry createTimetableEntry();

  /**
   * Returns a new object of class '<em>Food Lineup</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Food Lineup</em>'.
   * @generated
   */
  FoodLineup createFoodLineup();

  /**
   * Returns a new object of class '<em>Food</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Food</em>'.
   * @generated
   */
  Food createFood();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DomainPackage getDomainPackage();

} //DomainFactory
