/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.gmse.domain.DomainFactory
 * @model kind="package"
 * @generated
 */
public interface DomainPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "domain";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/gmse/Domain";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "domain";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DomainPackage eINSTANCE = org.xtext.gmse.domain.impl.DomainPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.FestivalImpl <em>Festival</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.FestivalImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getFestival()
   * @generated
   */
  int FESTIVAL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__NAME = 0;

  /**
   * The feature id for the '<em><b>Visitors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__VISITORS = 1;

  /**
   * The feature id for the '<em><b>Startdate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__STARTDATE = 2;

  /**
   * The feature id for the '<em><b>Enddate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__ENDDATE = 3;

  /**
   * The feature id for the '<em><b>Lineup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__LINEUP = 4;

  /**
   * The feature id for the '<em><b>Stages</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__STAGES = 5;

  /**
   * The feature id for the '<em><b>Timetable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__TIMETABLE = 6;

  /**
   * The feature id for the '<em><b>Food Lineup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL__FOOD_LINEUP = 7;

  /**
   * The number of structural features of the '<em>Festival</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FESTIVAL_FEATURE_COUNT = 8;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.LineupImpl <em>Lineup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.LineupImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getLineup()
   * @generated
   */
  int LINEUP = 1;

  /**
   * The feature id for the '<em><b>Artists</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEUP__ARTISTS = 0;

  /**
   * The number of structural features of the '<em>Lineup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINEUP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.ArtistImpl <em>Artist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.ArtistImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getArtist()
   * @generated
   */
  int ARTIST = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIST__NAME = 0;

  /**
   * The feature id for the '<em><b>Country</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIST__COUNTRY = 1;

  /**
   * The number of structural features of the '<em>Artist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ARTIST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.StagelistImpl <em>Stagelist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.StagelistImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getStagelist()
   * @generated
   */
  int STAGELIST = 3;

  /**
   * The feature id for the '<em><b>Stages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAGELIST__STAGES = 0;

  /**
   * The number of structural features of the '<em>Stagelist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAGELIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.StageImpl <em>Stage</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.StageImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getStage()
   * @generated
   */
  int STAGE = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Capacity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAGE__CAPACITY = 1;

  /**
   * The feature id for the '<em><b>Info</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAGE__INFO = 2;

  /**
   * The number of structural features of the '<em>Stage</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STAGE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.TimetableImpl <em>Timetable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.TimetableImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getTimetable()
   * @generated
   */
  int TIMETABLE = 5;

  /**
   * The feature id for the '<em><b>Timetable</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMETABLE__TIMETABLE = 0;

  /**
   * The number of structural features of the '<em>Timetable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMETABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.TimetableEntryImpl <em>Timetable Entry</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.TimetableEntryImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getTimetableEntry()
   * @generated
   */
  int TIMETABLE_ENTRY = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMETABLE_ENTRY__NAME = 0;

  /**
   * The feature id for the '<em><b>Day</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMETABLE_ENTRY__DAY = 1;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMETABLE_ENTRY__TIME = 2;

  /**
   * The feature id for the '<em><b>Stage</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMETABLE_ENTRY__STAGE = 3;

  /**
   * The number of structural features of the '<em>Timetable Entry</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMETABLE_ENTRY_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.FoodLineupImpl <em>Food Lineup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.FoodLineupImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getFoodLineup()
   * @generated
   */
  int FOOD_LINEUP = 7;

  /**
   * The feature id for the '<em><b>Foodlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD_LINEUP__FOODLIST = 0;

  /**
   * The number of structural features of the '<em>Food Lineup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD_LINEUP_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.impl.FoodImpl <em>Food</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.impl.FoodImpl
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getFood()
   * @generated
   */
  int FOOD = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD__TYPE = 1;

  /**
   * The feature id for the '<em><b>Place</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD__PLACE = 2;

  /**
   * The number of structural features of the '<em>Food</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FOOD_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.gmse.domain.days <em>days</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.gmse.domain.days
   * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getdays()
   * @generated
   */
  int DAYS = 9;


  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.Festival <em>Festival</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Festival</em>'.
   * @see org.xtext.gmse.domain.Festival
   * @generated
   */
  EClass getFestival();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Festival#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.gmse.domain.Festival#getName()
   * @see #getFestival()
   * @generated
   */
  EAttribute getFestival_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Festival#getVisitors <em>Visitors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visitors</em>'.
   * @see org.xtext.gmse.domain.Festival#getVisitors()
   * @see #getFestival()
   * @generated
   */
  EAttribute getFestival_Visitors();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Festival#getStartdate <em>Startdate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Startdate</em>'.
   * @see org.xtext.gmse.domain.Festival#getStartdate()
   * @see #getFestival()
   * @generated
   */
  EAttribute getFestival_Startdate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Festival#getEnddate <em>Enddate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Enddate</em>'.
   * @see org.xtext.gmse.domain.Festival#getEnddate()
   * @see #getFestival()
   * @generated
   */
  EAttribute getFestival_Enddate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.gmse.domain.Festival#getLineup <em>Lineup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Lineup</em>'.
   * @see org.xtext.gmse.domain.Festival#getLineup()
   * @see #getFestival()
   * @generated
   */
  EReference getFestival_Lineup();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.gmse.domain.Festival#getStages <em>Stages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Stages</em>'.
   * @see org.xtext.gmse.domain.Festival#getStages()
   * @see #getFestival()
   * @generated
   */
  EReference getFestival_Stages();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.gmse.domain.Festival#getTimetable <em>Timetable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Timetable</em>'.
   * @see org.xtext.gmse.domain.Festival#getTimetable()
   * @see #getFestival()
   * @generated
   */
  EReference getFestival_Timetable();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.gmse.domain.Festival#getFoodLineup <em>Food Lineup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Food Lineup</em>'.
   * @see org.xtext.gmse.domain.Festival#getFoodLineup()
   * @see #getFestival()
   * @generated
   */
  EReference getFestival_FoodLineup();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.Lineup <em>Lineup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Lineup</em>'.
   * @see org.xtext.gmse.domain.Lineup
   * @generated
   */
  EClass getLineup();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.gmse.domain.Lineup#getArtists <em>Artists</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Artists</em>'.
   * @see org.xtext.gmse.domain.Lineup#getArtists()
   * @see #getLineup()
   * @generated
   */
  EReference getLineup_Artists();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.Artist <em>Artist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Artist</em>'.
   * @see org.xtext.gmse.domain.Artist
   * @generated
   */
  EClass getArtist();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Artist#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.gmse.domain.Artist#getName()
   * @see #getArtist()
   * @generated
   */
  EAttribute getArtist_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Artist#getCountry <em>Country</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Country</em>'.
   * @see org.xtext.gmse.domain.Artist#getCountry()
   * @see #getArtist()
   * @generated
   */
  EAttribute getArtist_Country();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.Stagelist <em>Stagelist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stagelist</em>'.
   * @see org.xtext.gmse.domain.Stagelist
   * @generated
   */
  EClass getStagelist();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.gmse.domain.Stagelist#getStages <em>Stages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Stages</em>'.
   * @see org.xtext.gmse.domain.Stagelist#getStages()
   * @see #getStagelist()
   * @generated
   */
  EReference getStagelist_Stages();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.Stage <em>Stage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Stage</em>'.
   * @see org.xtext.gmse.domain.Stage
   * @generated
   */
  EClass getStage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Stage#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.gmse.domain.Stage#getName()
   * @see #getStage()
   * @generated
   */
  EAttribute getStage_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Stage#getCapacity <em>Capacity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Capacity</em>'.
   * @see org.xtext.gmse.domain.Stage#getCapacity()
   * @see #getStage()
   * @generated
   */
  EAttribute getStage_Capacity();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Stage#getInfo <em>Info</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Info</em>'.
   * @see org.xtext.gmse.domain.Stage#getInfo()
   * @see #getStage()
   * @generated
   */
  EAttribute getStage_Info();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.Timetable <em>Timetable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Timetable</em>'.
   * @see org.xtext.gmse.domain.Timetable
   * @generated
   */
  EClass getTimetable();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.gmse.domain.Timetable#getTimetable <em>Timetable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Timetable</em>'.
   * @see org.xtext.gmse.domain.Timetable#getTimetable()
   * @see #getTimetable()
   * @generated
   */
  EReference getTimetable_Timetable();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.TimetableEntry <em>Timetable Entry</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Timetable Entry</em>'.
   * @see org.xtext.gmse.domain.TimetableEntry
   * @generated
   */
  EClass getTimetableEntry();

  /**
   * Returns the meta object for the reference '{@link org.xtext.gmse.domain.TimetableEntry#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Name</em>'.
   * @see org.xtext.gmse.domain.TimetableEntry#getName()
   * @see #getTimetableEntry()
   * @generated
   */
  EReference getTimetableEntry_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.TimetableEntry#getDay <em>Day</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Day</em>'.
   * @see org.xtext.gmse.domain.TimetableEntry#getDay()
   * @see #getTimetableEntry()
   * @generated
   */
  EAttribute getTimetableEntry_Day();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.TimetableEntry#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.gmse.domain.TimetableEntry#getTime()
   * @see #getTimetableEntry()
   * @generated
   */
  EAttribute getTimetableEntry_Time();

  /**
   * Returns the meta object for the reference '{@link org.xtext.gmse.domain.TimetableEntry#getStage <em>Stage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Stage</em>'.
   * @see org.xtext.gmse.domain.TimetableEntry#getStage()
   * @see #getTimetableEntry()
   * @generated
   */
  EReference getTimetableEntry_Stage();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.FoodLineup <em>Food Lineup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Food Lineup</em>'.
   * @see org.xtext.gmse.domain.FoodLineup
   * @generated
   */
  EClass getFoodLineup();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.gmse.domain.FoodLineup#getFoodlist <em>Foodlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Foodlist</em>'.
   * @see org.xtext.gmse.domain.FoodLineup#getFoodlist()
   * @see #getFoodLineup()
   * @generated
   */
  EReference getFoodLineup_Foodlist();

  /**
   * Returns the meta object for class '{@link org.xtext.gmse.domain.Food <em>Food</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Food</em>'.
   * @see org.xtext.gmse.domain.Food
   * @generated
   */
  EClass getFood();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Food#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.gmse.domain.Food#getName()
   * @see #getFood()
   * @generated
   */
  EAttribute getFood_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Food#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.gmse.domain.Food#getType()
   * @see #getFood()
   * @generated
   */
  EAttribute getFood_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.gmse.domain.Food#getPlace <em>Place</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Place</em>'.
   * @see org.xtext.gmse.domain.Food#getPlace()
   * @see #getFood()
   * @generated
   */
  EAttribute getFood_Place();

  /**
   * Returns the meta object for enum '{@link org.xtext.gmse.domain.days <em>days</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>days</em>'.
   * @see org.xtext.gmse.domain.days
   * @generated
   */
  EEnum getdays();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DomainFactory getDomainFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.FestivalImpl <em>Festival</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.FestivalImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getFestival()
     * @generated
     */
    EClass FESTIVAL = eINSTANCE.getFestival();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FESTIVAL__NAME = eINSTANCE.getFestival_Name();

    /**
     * The meta object literal for the '<em><b>Visitors</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FESTIVAL__VISITORS = eINSTANCE.getFestival_Visitors();

    /**
     * The meta object literal for the '<em><b>Startdate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FESTIVAL__STARTDATE = eINSTANCE.getFestival_Startdate();

    /**
     * The meta object literal for the '<em><b>Enddate</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FESTIVAL__ENDDATE = eINSTANCE.getFestival_Enddate();

    /**
     * The meta object literal for the '<em><b>Lineup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FESTIVAL__LINEUP = eINSTANCE.getFestival_Lineup();

    /**
     * The meta object literal for the '<em><b>Stages</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FESTIVAL__STAGES = eINSTANCE.getFestival_Stages();

    /**
     * The meta object literal for the '<em><b>Timetable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FESTIVAL__TIMETABLE = eINSTANCE.getFestival_Timetable();

    /**
     * The meta object literal for the '<em><b>Food Lineup</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FESTIVAL__FOOD_LINEUP = eINSTANCE.getFestival_FoodLineup();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.LineupImpl <em>Lineup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.LineupImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getLineup()
     * @generated
     */
    EClass LINEUP = eINSTANCE.getLineup();

    /**
     * The meta object literal for the '<em><b>Artists</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINEUP__ARTISTS = eINSTANCE.getLineup_Artists();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.ArtistImpl <em>Artist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.ArtistImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getArtist()
     * @generated
     */
    EClass ARTIST = eINSTANCE.getArtist();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARTIST__NAME = eINSTANCE.getArtist_Name();

    /**
     * The meta object literal for the '<em><b>Country</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ARTIST__COUNTRY = eINSTANCE.getArtist_Country();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.StagelistImpl <em>Stagelist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.StagelistImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getStagelist()
     * @generated
     */
    EClass STAGELIST = eINSTANCE.getStagelist();

    /**
     * The meta object literal for the '<em><b>Stages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STAGELIST__STAGES = eINSTANCE.getStagelist_Stages();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.StageImpl <em>Stage</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.StageImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getStage()
     * @generated
     */
    EClass STAGE = eINSTANCE.getStage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STAGE__NAME = eINSTANCE.getStage_Name();

    /**
     * The meta object literal for the '<em><b>Capacity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STAGE__CAPACITY = eINSTANCE.getStage_Capacity();

    /**
     * The meta object literal for the '<em><b>Info</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STAGE__INFO = eINSTANCE.getStage_Info();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.TimetableImpl <em>Timetable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.TimetableImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getTimetable()
     * @generated
     */
    EClass TIMETABLE = eINSTANCE.getTimetable();

    /**
     * The meta object literal for the '<em><b>Timetable</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIMETABLE__TIMETABLE = eINSTANCE.getTimetable_Timetable();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.TimetableEntryImpl <em>Timetable Entry</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.TimetableEntryImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getTimetableEntry()
     * @generated
     */
    EClass TIMETABLE_ENTRY = eINSTANCE.getTimetableEntry();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIMETABLE_ENTRY__NAME = eINSTANCE.getTimetableEntry_Name();

    /**
     * The meta object literal for the '<em><b>Day</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIMETABLE_ENTRY__DAY = eINSTANCE.getTimetableEntry_Day();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIMETABLE_ENTRY__TIME = eINSTANCE.getTimetableEntry_Time();

    /**
     * The meta object literal for the '<em><b>Stage</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TIMETABLE_ENTRY__STAGE = eINSTANCE.getTimetableEntry_Stage();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.FoodLineupImpl <em>Food Lineup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.FoodLineupImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getFoodLineup()
     * @generated
     */
    EClass FOOD_LINEUP = eINSTANCE.getFoodLineup();

    /**
     * The meta object literal for the '<em><b>Foodlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FOOD_LINEUP__FOODLIST = eINSTANCE.getFoodLineup_Foodlist();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.impl.FoodImpl <em>Food</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.impl.FoodImpl
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getFood()
     * @generated
     */
    EClass FOOD = eINSTANCE.getFood();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOOD__NAME = eINSTANCE.getFood_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOOD__TYPE = eINSTANCE.getFood_Type();

    /**
     * The meta object literal for the '<em><b>Place</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FOOD__PLACE = eINSTANCE.getFood_Place();

    /**
     * The meta object literal for the '{@link org.xtext.gmse.domain.days <em>days</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.gmse.domain.days
     * @see org.xtext.gmse.domain.impl.DomainPackageImpl#getdays()
     * @generated
     */
    EEnum DAYS = eINSTANCE.getdays();

  }

} //DomainPackage
