/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Festival</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gmse.domain.Festival#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.Festival#getVisitors <em>Visitors</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.Festival#getStartdate <em>Startdate</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.Festival#getEnddate <em>Enddate</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.Festival#getLineup <em>Lineup</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.Festival#getStages <em>Stages</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.Festival#getTimetable <em>Timetable</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.Festival#getFoodLineup <em>Food Lineup</em>}</li>
 * </ul>
 *
 * @see org.xtext.gmse.domain.DomainPackage#getFestival()
 * @model
 * @generated
 */
public interface Festival extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Visitors</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visitors</em>' attribute.
   * @see #setVisitors(int)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_Visitors()
   * @model
   * @generated
   */
  int getVisitors();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getVisitors <em>Visitors</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visitors</em>' attribute.
   * @see #getVisitors()
   * @generated
   */
  void setVisitors(int value);

  /**
   * Returns the value of the '<em><b>Startdate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Startdate</em>' attribute.
   * @see #setStartdate(String)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_Startdate()
   * @model
   * @generated
   */
  String getStartdate();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getStartdate <em>Startdate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Startdate</em>' attribute.
   * @see #getStartdate()
   * @generated
   */
  void setStartdate(String value);

  /**
   * Returns the value of the '<em><b>Enddate</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enddate</em>' attribute.
   * @see #setEnddate(String)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_Enddate()
   * @model
   * @generated
   */
  String getEnddate();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getEnddate <em>Enddate</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enddate</em>' attribute.
   * @see #getEnddate()
   * @generated
   */
  void setEnddate(String value);

  /**
   * Returns the value of the '<em><b>Lineup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lineup</em>' containment reference.
   * @see #setLineup(Lineup)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_Lineup()
   * @model containment="true"
   * @generated
   */
  Lineup getLineup();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getLineup <em>Lineup</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lineup</em>' containment reference.
   * @see #getLineup()
   * @generated
   */
  void setLineup(Lineup value);

  /**
   * Returns the value of the '<em><b>Stages</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stages</em>' containment reference.
   * @see #setStages(Stagelist)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_Stages()
   * @model containment="true"
   * @generated
   */
  Stagelist getStages();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getStages <em>Stages</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stages</em>' containment reference.
   * @see #getStages()
   * @generated
   */
  void setStages(Stagelist value);

  /**
   * Returns the value of the '<em><b>Timetable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timetable</em>' containment reference.
   * @see #setTimetable(Timetable)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_Timetable()
   * @model containment="true"
   * @generated
   */
  Timetable getTimetable();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getTimetable <em>Timetable</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Timetable</em>' containment reference.
   * @see #getTimetable()
   * @generated
   */
  void setTimetable(Timetable value);

  /**
   * Returns the value of the '<em><b>Food Lineup</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Food Lineup</em>' containment reference.
   * @see #setFoodLineup(FoodLineup)
   * @see org.xtext.gmse.domain.DomainPackage#getFestival_FoodLineup()
   * @model containment="true"
   * @generated
   */
  FoodLineup getFoodLineup();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.Festival#getFoodLineup <em>Food Lineup</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Food Lineup</em>' containment reference.
   * @see #getFoodLineup()
   * @generated
   */
  void setFoodLineup(FoodLineup value);

} // Festival
