/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Food Lineup</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gmse.domain.FoodLineup#getFoodlist <em>Foodlist</em>}</li>
 * </ul>
 *
 * @see org.xtext.gmse.domain.DomainPackage#getFoodLineup()
 * @model
 * @generated
 */
public interface FoodLineup extends EObject
{
  /**
   * Returns the value of the '<em><b>Foodlist</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.gmse.domain.Food}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Foodlist</em>' containment reference list.
   * @see org.xtext.gmse.domain.DomainPackage#getFoodLineup_Foodlist()
   * @model containment="true"
   * @generated
   */
  EList<Food> getFoodlist();

} // FoodLineup
