/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Stagelist</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gmse.domain.Stagelist#getStages <em>Stages</em>}</li>
 * </ul>
 *
 * @see org.xtext.gmse.domain.DomainPackage#getStagelist()
 * @model
 * @generated
 */
public interface Stagelist extends EObject
{
  /**
   * Returns the value of the '<em><b>Stages</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.gmse.domain.Stage}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stages</em>' containment reference list.
   * @see org.xtext.gmse.domain.DomainPackage#getStagelist_Stages()
   * @model containment="true"
   * @generated
   */
  EList<Stage> getStages();

} // Stagelist
