/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timetable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gmse.domain.Timetable#getTimetable <em>Timetable</em>}</li>
 * </ul>
 *
 * @see org.xtext.gmse.domain.DomainPackage#getTimetable()
 * @model
 * @generated
 */
public interface Timetable extends EObject
{
  /**
   * Returns the value of the '<em><b>Timetable</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.gmse.domain.TimetableEntry}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timetable</em>' containment reference list.
   * @see org.xtext.gmse.domain.DomainPackage#getTimetable_Timetable()
   * @model containment="true"
   * @generated
   */
  EList<TimetableEntry> getTimetable();

} // Timetable
