/**
 * generated by Xtext 2.18.0
 */
package org.xtext.gmse.domain;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timetable Entry</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.gmse.domain.TimetableEntry#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.TimetableEntry#getDay <em>Day</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.TimetableEntry#getTime <em>Time</em>}</li>
 *   <li>{@link org.xtext.gmse.domain.TimetableEntry#getStage <em>Stage</em>}</li>
 * </ul>
 *
 * @see org.xtext.gmse.domain.DomainPackage#getTimetableEntry()
 * @model
 * @generated
 */
public interface TimetableEntry extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(Artist)
   * @see org.xtext.gmse.domain.DomainPackage#getTimetableEntry_Name()
   * @model
   * @generated
   */
  Artist getName();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.TimetableEntry#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(Artist value);

  /**
   * Returns the value of the '<em><b>Day</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.gmse.domain.days}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Day</em>' attribute.
   * @see org.xtext.gmse.domain.days
   * @see #setDay(days)
   * @see org.xtext.gmse.domain.DomainPackage#getTimetableEntry_Day()
   * @model
   * @generated
   */
  days getDay();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.TimetableEntry#getDay <em>Day</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Day</em>' attribute.
   * @see org.xtext.gmse.domain.days
   * @see #getDay()
   * @generated
   */
  void setDay(days value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(String)
   * @see org.xtext.gmse.domain.DomainPackage#getTimetableEntry_Time()
   * @model
   * @generated
   */
  String getTime();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.TimetableEntry#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(String value);

  /**
   * Returns the value of the '<em><b>Stage</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stage</em>' reference.
   * @see #setStage(Stage)
   * @see org.xtext.gmse.domain.DomainPackage#getTimetableEntry_Stage()
   * @model
   * @generated
   */
  Stage getStage();

  /**
   * Sets the value of the '{@link org.xtext.gmse.domain.TimetableEntry#getStage <em>Stage</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stage</em>' reference.
   * @see #getStage()
   * @generated
   */
  void setStage(Stage value);

} // TimetableEntry
